// ACTION TYPES
const COUNTER_DECREMENT = `COUNTER_DECREMENT`;
const COUNTER_INCREMENT = `COUNTER_INCREMENT`;
const COUNTER_MULTIPLY = `COUNTER_MULTIPLY`;

export { COUNTER_DECREMENT, COUNTER_INCREMENT, COUNTER_MULTIPLY };
