const COUNTRIES_FORM_SUBMIT = `COUNTRIES_FORM_SUBMIT`;
const SET_REGION_COUNTRIES = `SET_REGION_COUNTRIES`;
const SET_REGION_COUNTRIES_SETTED = `SET_REGION_COUNTRIES_SETTED`
const SET_COUNTRY = `SET_COUNTRY`;

export { COUNTRIES_FORM_SUBMIT, SET_REGION_COUNTRIES, SET_REGION_COUNTRIES_SETTED, SET_COUNTRY };
