const NEW_TODO_DEFAULT = {
  title: `Hello, world`,
  completed: true,
};

const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;
const TODOS_FILTER_COMPLETED = `TODOS_FILTER_COMPLETED`;
const TODOS_FILTER_PROGRESS = `TODOS_FILTER_PROGRESS`;

export {
  NEW_TODO_DEFAULT,
  TODOS_FILTER_ALL,
  TODOS_FILTER_COMPLETED,
  TODOS_FILTER_PROGRESS,
};
