const SET_COUNTRIES_PARAMS = `SET_COUNTRIES_PARAMS`;
const SET_REGION_COUNTRIES = `SET_REGION_COUNTRIES`;
const SET_COUNTRY = `SET_COUNTRY`;
const RESET_COUNTRY = `RESET_COUNTRY`;
const SET_COUNTRIES_SELECTED = `SET_COUNTRIES_SELECTED`;
const SET_COUNTRIES_ADDITIONAL_INFO = `SET_COUNTRIES_ADDITIONAL_INFO`;
const SET_BATTLE_RESULT = `SET_BATTLE_RESULT`;
const SET_RESET_BATTLE = `SET_RESET_BATTLE`;
const RESET_BATTLE = `RESET_BATTLE`;

export { SET_COUNTRIES_PARAMS, SET_REGION_COUNTRIES, SET_COUNTRY, RESET_COUNTRY, SET_COUNTRIES_SELECTED, SET_COUNTRIES_ADDITIONAL_INFO, SET_BATTLE_RESULT, SET_RESET_BATTLE, RESET_BATTLE };
